module.exports = Object.freeze({
    INSERT_BOOK: "INSERT BOOK (NAME, NUM_PAGES) VALUES(?,?)",
    SELECT_ALL_BOOKS: "SELECT * FROM BOOK",
    UPDATE_BOOK: "UPDATE BOOK SET NAME = ?, NUM_PAGES = ? WHERE ID = ?",
    SELECT_BOOK_BY_ID: "SELECT * FROM BOOK WHERE ID = ?"
});