DROP TABLE IF EXISTS `RECIPE`.`HAS_INGREDIENT`;
DROP TABLE IF EXISTS `RECIPE`.`HAS_STEP`;
DROP TABLE IF EXISTS `RECIPE`.`INGREDIENT`;
DROP TABLE IF EXISTS `RECIPE`.`RECIPE`;
DROP TABLE IF EXISTS `RECIPE`.`USER`;
DROP TABLE IF EXISTS `RECIPE`.`BOOK`;
DROP TABLE IF EXISTS `RECIPE`.`TYPE_OF_PLATE`;
DROP SCHEMA IF EXISTS `RECIPE`;