/*---------------Sacar los ingredientes de una receta ---------------*/
SELECT DISTINCT INGREDIENT.ID, INGREDIENT.NAME, INGREDIENT.CALORIES_PER_100_GRAMS, INGREDIENT.CREATION_DATETIME 
FROM INGREDIENT 
INNER JOIN HAS_INGREDIENT ON HAS_INGREDIENT.ID_INGREDIENT = INGREDIENT.ID 
INNER JOIN RECIPE ON @ID_RECIPE = HAS_INGREDIENT.ID_RECIPE

/*---------------Sacar los pasos de una receta ---------------*/
SELECT DISTINCT STEP.STEP
FROM STEP
INNER JOIN HAS_STEP ON HAS_STEP.ID_STEP = STEP.ID
INNER JOIN RECIPE ON @ID_RECIPE = HAS_STEP.ID_RECIPE;