module.exports = Object.freeze({
    INSERT_RECIPE: "INSERT RECIPE (NAME, PLATE, CALORIES, PHOTO_URL, PHOTO_URL_BACKUP, GRADE, LAST_MODIFICATION_DATETIME) VALUES(?,?,?,?,?,?,?)",
    SELECT_ALL_RECIPES: "SELECT * FROM RECIPE",
    UPDATE_RECIPE: "UPDATE RECIPE SET NAME = ?, PLATE = ?, CALORIES = ?, PHOTO_URL = ?, PHOTO_URL_BACKUP = ?, GRADE = ?, LAST_MODIFICATION_DATETIME = ? WHERE ID = ?",
    SELECT_RECIPE_BY_ID: "SELECT * FROM RECIPE WHERE ID = ?",
    SELECT_RECIPE_INGREDIENTS: "SELECT DISTINCT INGREDIENT.ID, INGREDIENT.NAME, INGREDIENT.CALORIES_PER_100_GRAMS, INGREDIENT.CREATION_DATETIME, HAS_INGREDIENT.QUANTITY, HAS_INGREDIENT.MEASURE_UNIT FROM INGREDIENT INNER JOIN HAS_INGREDIENT ON HAS_INGREDIENT.ID_INGREDIENT = INGREDIENT.ID INNER JOIN RECIPE ON ? = HAS_INGREDIENT.ID_RECIPE",
    SELECT_RECIPE_STEPS: "SELECT DISTINCT STEP.ID, STEP.STEP, STEP.CREATION_DATETIME FROM STEP INNER JOIN HAS_STEP ON HAS_STEP.ID_STEP = STEP.ID INNER JOIN RECIPE ON ? = HAS_STEP.ID_RECIPE",
    SELECT_RECIPE_BOOK: "SELECT DISTINCT BOOK.ID, BOOK.NAME, BOOK.NUM_PAGES, BOOK.CREATION_DATE FROM BOOK INNER join RECIPE ON BOOK.id = ?"
});