module.exports = Object.freeze({
    INSERT_RECIPE: "INSERT RECIPE (NAME, PLATE, CALORIES, PHOTO_URL, PHOTO_URL_BACKUP, GRADE, LAST_MODIFICATION_DATETIME) VALUES(?,?,?,?,?,?,?)",
    SELECT_ALL_RECIPES: "SELECT * FROM RECIPE",
    UPDATE_RECIPE: "UPDATE RECIPE SET NAME = ?, PLATE = ?, CALORIES = ?, PHOTO_URL = ?, PHOTO_URL_BACKUP = ?, GRADE = ?, LAST_MODIFICATION_DATETIME = ? WHERE ID = ?",
    SELECT_RECIPE_BY_ID: "SELECT * FROM RECIPE WHERE ID = ?"
});